/*

 GOOD_FILE_NAME_FOR_A_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\max\Desktop\gbtd_22_tile_designer\good_file_name.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define good_file_name_for_a_mapWidth 20
#define good_file_name_for_a_mapHeight 18
#define good_file_name_for_a_mapBank 0

extern unsigned char good_file_name_for_a_map[];

/* End of GOOD_FILE_NAME_FOR_A_MAP.H */
