/*

 GOOD_FILE_NAME_FOR_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define good_file_nameBank 0
/* Start of tile array. */
extern unsigned char good_file_name[];

/* End of GOOD_FILE_NAME_FOR_TILES.H */
